stages:
  - prepare
  - build

variables:
  CACHE_FALLBACK_KEY: "main"
  CMAKE_BUILD_TYPE: "Release"
  # This variable has to be overridden to allow caching of conan packages, which must be updated the project dir to get cached.  This is where conan will look for the `.conan` directory
  CONAN_USER_HOME: "$CI_PROJECT_DIR"
  CONAN_USERNAME: "gitlab-ci"
  CONAN_REFERENCE: "advanced-flex-server/0.9"
  CONAN_CHANNEL: "gitlab-ci"
  CONAN_UPLOAD: "https://systemicai.jfrog.io/artifactory/api/conan/afs-http@True@systemicai-afshttp"
  CONAN_REMOTE: "https://systemicai.jfrog.io/artifactory/api/conan/afs-http@True@systemicai-afshttp"
  # These 4 variables are tightly coupled and change with the compiler version used
  LLVM_VERSION: "11"
  CC: "clang"
  CXX: "clang++"
  CXX_STANDARD: "20"
  CXX_STANDARD_LIBRARY: "libstdc++"
  CXX_CONTAINER: "registry.gitlab.com/k8s.makerlabs.us/build-cxx:ubi8-clang-${LLVM_VERSION}"
  #CXX_FLAGS: "-std=c++20 -stdlib=libc++ -lstdc++fs"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  # Don't just cache $CONAN_USER_HOME because that includes credentials (and complicates scripts)
  - "$CONAN_USER_HOME/.conan/data"

.build-template: &build-template
  tags: 
  - cpp
  before_script:
  - conan profile new default --detect
  - conan profile update env.CC=${CC} default
  - conan profile update env.CXX=${CXX} default
  #- conan profile update env.CXX_FLAGS="${CXX_FLAGS}" default
  - conan profile update settings.compiler.libcxx=${CXX_STANDARD_LIBRARY} default
  - conan profile update settings.compiler.cppstd=${CXX_STANDARD} default
  # libmysqlclient uses C++ reserved words from the cxx17/20 standard as member variables, so have to allow a lower c++ standard for it
  - conan profile update settings.libmysqlclient:compiler.cppstd=14 default
  - conan profile show default
  - conan user
  - conan remote add systemicai-afshttp https://systemicai.jfrog.io/artifactory/api/conan/afs-http
  - '[[ ! -z "${CONAN_PASSWORD}" ]] && conan user -r systemicai-afshttp -p "${CONAN_PASSWORD}" "${CONAN_LOGIN_USERNAME}"'

dependencies:
  stage: prepare
  image: ${CXX_CONTAINER}
  script:
  - mkdir -p build
  - pushd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - make dependencies # Populates the cache directory with built libraries for boost, etc
  - popd # build
  <<: *build-template

clang:
  artifacts:
    reports:
      junit: build/coverage-tests.report.xml
    paths:
      - build/scan-build
      - build/coverage
      - build/dependencies.html
      - build/dist
  stage: build
  image: ${CXX_CONTAINER}
  script:
  - mkdir -p build
  - pushd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DEXTRA_LIBS=stdc++fs ..
  - scan-build -o scan-build/reports --exclude ${CONAN_USER_HOME}/.conan/data make -j 10
  - popd # build
  <<: *build-template
