
variables:
    CONAN_USERNAME: "user"
    CONAN_REFERENCE: "advanced-flex-server/0.9"
    CONAN_CHANNEL: "channel"
    CONAN_LOGIN_USERNAME: "user"
    CONAN_UPLOAD: "https://systemicai.jfrog.io/artifactory/afs-http/"

.build-template: &build-template
    before_script:
        - sudo pip install --upgrade conan_package_tools
        - conan user
    script:
        - python build.py

clang-10.0:
    image: conanio/clang10
    variables:
        CONAN_CLANG_VERSIONS: "10"
    <<: *build-template

